ports:
  - port: 8000
    description: for server
    onOpen: notify
  - port: 3000
    description: for FE
    onOpen: open-browser
    visibility: public
  - port: 80
    onOpen: ignore

tasks:
  - name: Server
    init: |
      chmod +x setup.sh
      ./setup.sh $(gp url 8000)
      docker compose up -d
